import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002204",
        "surface-dim": "#d9dadb",
        "tertiary-container": "#002805",
        "surface-tint": "#465f88",
        "surface-variant": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#708ab5",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#44474e",
        "tertiary": "#000e01",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "tertiary-fixed": "#a3f69c",
        "on-secondary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#88d982",
        "outline": "#74777f",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed-dim": "#e9c349",
        "secondary-fixed": "#ffe088",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#241a00",
        "on-primary-fixed-variant": "#2d476f",
        "secondary": "#735c00",
        "inverse-surface": "#2e3132",
        "secondary-container": "#fed65b",
        "on-surface": "#191c1d",
        "error": "#ba1a1a",
        "primary-container": "#002147",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#4a994a",
        "primary-fixed": "#d6e3ff",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "inverse-primary": "#aec7f6",
        "primary": "#000a1e",
        "on-secondary-container": "#745c00",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#aec7f6",
        "on-primary-fixed": "#001b3d",
        "on-tertiary-fixed-variant": "#005312",
        "inverse-on-surface": "#f0f1f2"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
